### ISSUE TITLE
Create container for testing Ember apps

### ISSUE THREAD

**Issue by chinthakagodawita** [Sitback/docker-containers#34]
Should have a variation of the below (lifted from a project):

```dockerfile
FROM sitback/base:ubuntu-14.04
MAINTAINER Chinthaka Godawita <chin@sitback.com.au>

# Add node 5.x via nodesource.
RUN curl -sL https://deb.nodesource.com/setup_5.x | bash -
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs

# Setup application base directory.
RUN mkdir -p /server
WORKDIR /server

# Chrome repos.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update

# Chrome + XVFB for headless support
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y xvfb google-chrome-stable

# Ember global requirements.
RUN npm install -g bower ember-cli
```

**Comment by jrhodes-sitback** [comment]
Thanks for creating this Chin. I think we need a quicker build time for
tests.

On Thu, May 26, 2016 at 9:24 AM Chin Godawita <notifications@github.com>
wrote:

> Should have a variation of the below (lifted from a project):
>
> FROM sitback/base:ubuntu-14.04MAINTAINER Chinthaka Godawita <chin@sitback.com.au>
> # Add node 5.x via nodesource.RUN curl -sL https://deb.nodesource.com/setup_5.x | bash -RUN DEBIAN_FRONTEND=noninteractive apt-get install -y nodejs
> # Setup application base directory.RUN mkdir -p /serverWORKDIR /server
> # Chrome repos.RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'RUN apt-get update
> # Chrome + XVFB for headless supportRUN DEBIAN_FRONTEND=noninteractive apt-get install -y xvfb google-chrome-stable
> # Ember global requirements.RUN npm install -g bower ember-cli
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Sitback/docker-containers/issues/34>
>
-- 
Jonathan Rhodes | Technical Lead

-- 
 

 39 - 41 Lower Fort Street, The Rocks, Sydney. 2000
<https://www.facebook.com/pages/Sitback/159057074134649>  
<https://twitter.com/Sitback>  
<http://www.linkedin.com/company/1482531?trk=tyah&trkInfo=tarId%3A1413439096225%2Ctas%3ASitback%2Cidx%3A2-1-4>
<http://www.sitback.com.au>
