### ISSUE TITLE
Deprecate PHP 5.3 & 5.4 support

### ISSUE THREAD

**Issue by chinthakagodawita** [Sitback/docker-containers#48]
[PHP 5.3 and 5.4 are no longer supported](http://php.net/supported-versions.php) and [Ubuntu 12.04 goes end-of-life in April 2017](https://www.ubuntu.com/info/release-end-of-life).

Builds for these containers will stop on the 3rd of April 2017 and the Docker image repositories will be removed on the 3rd of July. Plan accordingly.

**Comment by mlhoque** [comment]
Deleted PHP 5.3 and 5.4 images
Deleted ubuntu 12.04
