### ISSUE TITLE
Create a CentOS 7 base container

### ISSUE THREAD

**Issue by chinthakagodawita** [Sitback/docker-containers#66]
We need this for LTS PHP 5.4 support unfortunately. Some of our clients won't be moving across to 5.6 any time soon due to enterprise requirements.

This should contain the following features to bring it to feature parity with the Ubuntu 14.04 image:
* Services handled through `supervisord`
* `Australia/Sydney` set as the default timezone
* `en_AU` set as the default locale
* The following software:
  * Base build tools (`gcc`—or `clang`, `make`, `autoconf`, `automake`)
  * `curl`
  * `telnet`
  * `rsync`
  * `wget`
  * `nano`
  * `vim`
  * `net-tools`
  * `git`
  * `zip` & `unzip`
  * `cron`
  * `python`
  * `supervisor-stdout` (may need to be installed via `easy_install`, [see the Ubuntu Dockerfile](https://github.com/Sitback/docker-containers/blob/master/base/ubuntu-14.04/Dockerfile#L38))
* rspec tests

**Comment by tarunbhargav83** [comment]
created CentOS 7 base containers
